name: Build Windows executable

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4.1.6
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build executable
      run: pyinstaller --onefile main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: main.exe
        path: dist/main.exe
