name: Build Windows executable

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4.1.6
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build executable
      run: pyinstaller --onefile main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: main.exe
        path: dist/main.exe

      # 获取最新的 commit 信息
    - name: Get latest commit message
      id: commit_message
      run: |
        echo ::set-output name=commit_message::$(git log -1 --pretty=%B)

      # 创建一个新的标签
    - name: Create tag
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        # 获取最新的 commit 信息
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        # 生成标签名，包含日期和 commit 信息
        TAG_NAME="v$(date +%Y.%m.%d)-$(echo "$COMMIT_MESSAGE" | head -n 1 | sed 's/[^a-zA-Z0-9.-]/_/g')"
        # 创建并推送标签
        git tag -a "$TAG_NAME" -m "$COMMIT_MESSAGE"
        git push origin "$TAG_NAME"
      

      # 创建一个新的发布
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: $TAG_NAME_SANITIZED
        release_name: "Release $TAG_NAME_SANITIZED"
        draft: false
        prerelease: false


    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/main.exe
        asset_name: main.exe
        asset_content_type: application/octet-stream
